language: node_js
node_js:
  - 12.14.1
before_install:
  - npm i -g yarn
install:
  - cd web/
  - yarn install
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
addons:
  ssh_known_hosts:
    - 192.64.115.227
jobs:
  include:
    - if: branch = development
      script:
        cp ../.env.development .env;
        yarn run build;
      before_deploy:
        - cd ../
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash ./deploy-staging.sh
          on:
            branch: development
    - if: branch = master
      script:
        cp ../.env.production .env;
        yarn run build;
      before_deploy:
        - cd ../
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash ./deploy-production.sh
          on:
            branch: master
