#!/bin/bash
echo $HOST_PRODUCTION
DEPLOY_BASE_DIR=/var/www/CsgoHoldem-Frontend
DEPLOY_RELEASES=$DEPLOY_BASE_DIR/releases
DEPLOY_SYMLINK=$DEPLOY_BASE_DIR/current
DEPLOYMENT_DIR=$DEPLOY_RELEASES/$(date +"%Y%m%d%H%M%S")

sftp  $USER_PRODUCTION@$HOST_PRODUCTION:$DEPLOY_RELEASES <<EOF
mkdir ${DEPLOYMENT_DIR}
cd ${DEPLOYMENT_DIR}
lcd web/build
put -r .
exit
EOF

ssh $USER_PRODUCTION@$HOST_PRODUCTION << EOF
   ln -sfn ${DEPLOYMENT_DIR} ${DEPLOY_SYMLINK}
EOF
